name: 'ktlint'
description: 'Runs ktlint and adds comments with ReviewDog'
inputs:
  githubToken:
    description: 'GitHub token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.githubToken }}
