name: Linting

on: [pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: openjdk:11.0.1-jdk-slim-stretch
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      - name: Configure container
        run: |
          apt-get update && apt-get -y install curl
      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.35.0/ktlint && chmod a+x ktlint
      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
      - name: Run ktlint
        run: |
          ktlint | tee /tmp/ktlint.log
          cat /tmp/ktlint.log
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat /tmp/ktlint.log | ./bin/reviewdog -f=checkstyle -name="ktlint" -reporter=github-pr-check

