on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    runs-on: ubuntu-latest
    container: openjdk:11.0.1-jdk-slim-stretch
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: ./gradlew test
      - name: Jacoco reports
        run: ./gradlew testCoverage
      - name: Upload test results to Codacy
        run: |
          apt-get update && apt-get install -y curl jq
          curl -LS -o codacy-coverage-reporter-assembly.jar "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')"
          java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

