name: 'Codacy Upload'
description: 'Uploads test coverage reports to Codacy'
inputs:
  reportPath:
    description: 'Path to Jacoco XML report'
    default: 'build/reports/jacoco/test/jacocoTestReport.xml'
    required: true
  codacyToken:
    description: 'Token to auth to Codacy with'
    required: true
  commitId:
    description: 'Commit to upload coverage for'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CODACY_PROJECT_TOKEN: ${{ inputs.codacyToken }}
    REPORT_PATH: ${{ inputs.reportPath }}
    COMMIT_ID: ${{ inputs.commitId }}

